Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/03/2026
Var
// Seção de Declarações das variáveis 
n : inteiro

Inicio
escreva("Digite um número?")
leia(n)

se (n % 2 = 0) entao
escreva("PAR")
senao
escreva("IMPAR")
fimse


Fimalgoritmo