Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/03/2026
Var
// Seção de Declarações das variáveis 
ano : inteiro

Inicio
escreva("Digite o ano?")
leia(ano)

se (ano % 4 = 0) entao
escreva("Bissexto")
senao
escreva("Não")
fimse


Fimalgoritmo